### ISSUE TITLE
Initial file checklist (English)

### ISSUE THREAD

**Issue by akpc** [qulacs/qulacs-rtd#2]
This issue is used to check the progress of writing individual files.
- [x] Index -> toc, links, logo
- [x] About -> ( todo: github-flavored markdown convert)
- [x] Getting started, install
- [x] Trouble shooting
- [x] Python tutorial 1
- [x] Python tutorial advanced
- [x] C++ tutorial
- [x] Quantum Native Dojo - VQE
- [x] Quantum Native Dojo - NISQ
- [x] English API ( inside cppsim source files)

**Comment by akpc** [comment]
- [ ] Index -> toc, links, logo
- [ ] About -> ( todo: github-flavored markdown convert)
- [*] Getting started, install
- [*] Trouble shooting
- [ ] Python tutorial 1
- [ ] Python tutorial advanced
- [ ] C++ tutorial
- [ ] Quantum Native Dojo - VQE
- [ ] Quantum Native Dojo - NISQ
- [ ] English API ( inside cppsim source files)

**Comment by akpc** [comment]
We have all the files!
closing this issue.
